version: "3.5"
volumes:
  z-way-server_config_zddx: {}
  z-way-server_automation-storage: {}
  z-way-server_automation-userModules: {}
  z-way-server_htdocs-smarthome-user: {}
services:
  z-way-server:
    build: .
    image: "z-way-server"
    container_name: z-way-server
    restart: always
    volumes:
      - "z-way-server_config_zddx:/opt/z-way-server/config/zddx"
      - "z-way-server_automation-storage:/opt/z-way-server/automation/storage"
      - "z-way-server_automation-userModules:/opt/z-way-server/automation/userModules"
      - "z-way-server_htdocs-smarthome-user:/opt/z-way-server/htdocs/smarthome/user/"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/var/run/dbus:/var/run/dbus"
      - "/var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket"
    devices:
      - "/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyS4"
    network_mode: "host"